### ISSUE TITLE
Rollup reports circular dependency import between one.js and all.js files

### ISSUE THREAD

**Issue by jedrzejchalubek** [syntax-tree/xast-util-to-xml#3]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.0.1

### Steps to reproduce

Bundling package using rollup.js gives this message:

`Circular dependency: ../../node_modules/xast-util-to-xml/lib/one.js -> ../../node_modules/xast-util-to-xml/lib/all.js -> ../../node_modules/xast-util-to-xml/lib/one.js`

The bundle

### Expected behavior

The `one.js` and `all.js` files should not import each other

### Actual behavior

The `one.js` and `all.js` import each other causing circular dependency

### Affected runtime and version

node@19

### Build and bundle tools

Rollup

**Comment by wooorm** [comment]
Released in [3.0.2](https://github.com/syntax-tree/xast-util-to-xml/releases/tag/3.0.2)!
